const itemAT = {
  INIT_ITEMS_REQUESTED: 'INIT_ITEMS_REQUESTED',
  INIT_ITEMS_SUCCESS: 'INIT_ITEMS_SUCCESS',
  INIT_TYPES_SUCCESS: 'INIT_TYPES_SUCCESS',
  INIT_SIZES_SUCCESS: 'INIT_SIZES_SUCCESS',
  ADD_ITEM_SUCCESS: 'ADD_ITEM_SUCCESS',
  INIT_ITEMS_ERROR: 'INIT_ITEMS_ERROR',
  GET_ITEM_REQUESTED: 'GET_ITEM_REQUESTED',
  GET_ITEM_SUCCEESS: 'GET_ITEM_SUCCESS',


  TODO: 'TODO',
};

export {itemAT};
