const itemAT = {
  INIT_ITEMS_REQUESTED: 'INIT_ITEMS_REQUESTED',
  INIT_ITEMS_SUCCESS: 'INIT_ITEMS_SUCCESS',
  INIT_ITEMS_ERROR: 'INIT_ITEMS_ERROR',

  ADD_PLAYER_REQUESTED: 'ADD_PLAYER_REQUESTED',
  ADD_PLAYER_SUCCESS: 'ADD_PLAYER_SUCCESS',
  ADD_PLAYER_ERROR: 'ADD_PLAYER_ERROR',

  INIT_PONIES_REQUESTED: 'INIT_PONIES_REQUESTED',
  INIT_PONIES_SUCCESS: 'INIT_PONIES_SUCCESS',
  INIT_PONIES_ERROR: 'INIT_PONIES_ERROR',

  TODO: 'TODO',
};

export {itemAT};
